{"uuid": "34c009d8-d935-436b-96fd-10db30c9e11d", "children": ["6ae28b45-1e55-4655-9645-b6e039e92dc8"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/Users/pramod/PycharmProjects/PyWebAutomation0x/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pramod/PycharmProjects/PyWebAutomation0x/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pramod/PycharmProjects/PyWebAutomation0x/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/pramod/PycharmProjects/PyWebAutomation0x/tests/vwoLoginTests/conftest.py\", line 8, in setup\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"/Users/pramod/PycharmProjects/PyWebAutomation0x/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/Users/pramod/PycharmProjects/PyWebAutomation0x/venv/lib/python3.11/site-packages/selenium/webdriver/common/service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1693221612946, "stop": 1693221612951}], "start": 1693221612946, "stop": 1693221613064}